sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t willempoort/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true willempoort/docker-react npm run test

